# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/eisenbahn/Schreibtisch/AAA_Florian_BA/VIvado/Programme/BA/BA_Florian/BA_Florian.srcs/sources_1/ip/DMX_BRAM_ONE/DMX_BRAM_ONE.xci
# IP: The module: 'DMX_BRAM_ONE' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/eisenbahn/Schreibtisch/AAA_Florian_BA/VIvado/Programme/BA/BA_Florian/BA_Florian.gen/sources_1/ip/DMX_BRAM_ONE/DMX_BRAM_ONE_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DMX_BRAM_ONE'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/eisenbahn/Schreibtisch/AAA_Florian_BA/VIvado/Programme/BA/BA_Florian/BA_Florian.srcs/sources_1/ip/DMX_BRAM_ONE/DMX_BRAM_ONE.xci
# IP: The module: 'DMX_BRAM_ONE' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/eisenbahn/Schreibtisch/AAA_Florian_BA/VIvado/Programme/BA/BA_Florian/BA_Florian.gen/sources_1/ip/DMX_BRAM_ONE/DMX_BRAM_ONE_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DMX_BRAM_ONE'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
